apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adservice-uploads-pvc
  namespace: adservice
  labels:
    app: adservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem